// <auto-generated />
namespace Homework1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddSurvey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSurvey));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141331107_Add-Survey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
